# Generated by Django 5.1.5 on 2025-02-14 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'managed': False, 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': False, 'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogos'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'managed': False, 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallesdecompra',
            options={'managed': False, 'verbose_name': 'Detalles de compra', 'verbose_name_plural': 'Detalles de compras'},
        ),
        migrations.AlterModelOptions(
            name='detallesdelcarrito',
            options={'managed': False, 'verbose_name': 'Detalles del carrito', 'verbose_name_plural': 'Detalles de los carritos'},
        ),
        migrations.AlterModelOptions(
            name='detallesdeventa',
            options={'managed': False, 'verbose_name': 'Detalles de venta', 'verbose_name_plural': 'Detalles de ventas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False, 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'managed': False, 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
